//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : ������
//  @ File Name : IdUtils.java
//  @ Date : 2012-11-08
//  @ Author : 
//
//

package cn.gov.spb.cq.yzglfzgj.config;


public class IdUtils {
//	private static final transient Logger log = Logger.getLogger(IdUtils.class);

	/**
	 * <p>
	 * 生成UUID主键
	 * </p>
	 * 
	 * @param len
	 *            位数
	 * @return 主键
	 */
	public static String createUUID(int len) {

		String uuid = java.util.UUID.randomUUID().toString()
				.replaceAll("-", "");
		return uuid.substring(0, len);
	}

	public static void main(String args[]) {
		
		for(int i=0;i<99;i++){
			System.out.println(IdUtils.createUUID(32));
		}
		
	
		
		// log.info();
	}
	
	
	/**
	 * <p>
	 * 生成认证码
	 * </p>
	 * <ol>
	 * [功能概要] <div>生成邮箱和手机认证码，用于用户确认邮箱和手机。</div> <div>邮箱：33位UUID码。</div>
	 * <div>手机：6位数字和小写字母的组合。</div>
	 * </ol>
	 * 
	 * @param type
	 *            1：邮箱 2：手机
	 * @return 邮箱认证码
	 */
/*	public static String createVerifyInfo(String type) {
		//邮箱
		if ("1".equals(type)) {
			return java.util.UUID.randomUUID().toString().replaceAll("-", "");
		} else {
			return WebUtils.getRandomNum(6);
		}

	}*/
	
	/**
	 * <p>
	 * 生成外部订单编号
	 * </p>
	 * 
	 * @param orderType
	 *            订单类型 P:普通订单 Y:预订订单
	 * @return 外部订单编号
	 */
	/*public static String createOuterOrderId(String orderType) {

		String id = "";

		if (Validator.isNullEmpty(orderType)) {
			return id;
		}

		id += orderType.toUpperCase();

		SimpleDateFormat format = new SimpleDateFormat("yyyyMMddHHmmssS");
		String dateStr = format.format(new Date());

		// 年月日
		id += dateStr.substring(2, 8);

		id += "-";

		// 秒数
		// String h = dateStr.substring(8, 10);
		// String m = dateStr.substring(10, 12);
		// String s = dateStr.substring(12, 14);
		// DecimalFormat df = new DecimalFormat();
		// df.applyPattern("00000");
		// id += df.format(Integer.parseInt(h) * 60 * 60 + Integer.parseInt(m) *
		// 60 + Integer.parseInt(s));

		// 12位随机数字
		Random random = new Random();
		for (int i = 0; i < 10; i++) {
			String rand = String.valueOf(random.nextInt(10));
			id += rand;
		}

		// 毫秒数
		// DecimalFormat df1 = new DecimalFormat();
		// df1.applyPattern("000");
		// id += df1.format(Integer.parseInt(dateStr.substring(14,
		// dateStr.length())));

		return id;

	}*/
}
